---
title: "World Graph"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
```


##########################################################

For the TALENT MIGRATION TAB

##########################################################


```{r}
country_migration = read_csv("C:/Northeastern R files/ie 6600/country_migration_public.csv", show_col_types = FALSE)
industry_migration = read_csv("C:/Northeastern R files/ie 6600/industry_migration_public.csv", show_col_types = FALSE)
skill_migration = read_csv("C:/Northeastern R files/ie 6600/skill_migration_public.csv", show_col_types = FALSE)

```


World Graph 

```{r}

base_country = "India"

base_country_lat <- country_migration %>%  filter(base_country_name %in% base_country) 
base_country_lat <- base_country_lat$base_lat[1]

base_country_lon <- country_migration %>%  filter(base_country_name %in% base_country) 
base_country_lon <- base_country_lon$base_long[1]


talent_graph <- subset(country_migration, select = c(base_country_name, target_country_name, target_lat, target_long, net_per_10K_2017,net_per_10K_2018,net_per_10K_2019))
talent_graph$Value <- round((talent_graph$net_per_10K_2017 + talent_graph$net_per_10K_2018 + talent_graph$net_per_10K_2019)/3, digits = 2)
talent_graph <- subset(talent_graph, select = c(base_country_name, target_country_name, target_lat, target_long, Value))


positive <- talent_graph %>% filter(base_country_name %in% base_country) %>% filter(Value > 0) 
positive <- positive[order(positive$Value),][1:5,]
positive <- na.omit(positive)


negative <- talent_graph %>% filter(base_country_name %in% base_country) %>% filter(Value < 0) 
negative <- negative[order(negative$Value),][1:5,]
negative <- na.omit(negative)


maps::map('world',col="#f2f2f2", fill=TRUE, bg="lightgray", lwd=0.05, mar=rep(0,4),border=0, ylim=c(-80,80))

points(x=negative$target_long, y=negative$target_lat, col="red", cex=2, pch=20)
text(negative$target_country_name , x=negative$target_long, y=negative$target_lat,  col="red", cex=1, pos=4)

points(x=positive$target_long, y=positive$target_lat, col="green", cex=2, pch=20)
text(positive$target_country_name , x=positive$target_long, y=positive$target_lat,  col="green", cex=1, pos=4)

points(x=base_country_lon, y=base_country_lat, col="black", cex=2, pch=20)
text(base_country , x=base_country_lon, y=base_country_lat,  col="black", cex=1, pos=1)

Country_positive <- subset(positive, select = c(target_country_name, Value))

Country_negative <- subset(negative, select = c(target_country_name, Value))

```

```{r}
#install.packages("leaflet")
```
```{r}
library('leaflet')

```

```{r}
iconc <- makeAwesomeIcon(markerColor = 'green')
iconb <- makeAwesomeIcon( markerColor = 'red')
icona <- makeAwesomeIcon( markerColor = 'black')


m <- leaflet()
m <- addTiles(m)
m <- addAwesomeMarkers(m, lng=negative$target_long, lat=negative$target_lat, popup=negative$target_country_name, icon = iconb) %>%addAwesomeMarkers(m, lng=positive$target_long, lat=positive$target_lat, popup=positive$target_country_name, icon=iconc ) %>%  addAwesomeMarkers(m, lng=base_country_lon, lat=base_country_lat, popup=base_country, icon=icona )
m

```


Industry Migration

```{r}

industry_table <- subset(industry_migration, select = c(industry_name, net_per_10K_2017, net_per_10K_2018, net_per_10K_2019))

industry_table$industry_Value <- round((industry_table$net_per_10K_2017 + industry_table$net_per_10K_2018 + industry_table$net_per_10K_2019)/3, digits = 2)

industry_table <- subset(industry_table, select = c(industry_name, industry_Value))

industry_table <- aggregate(industry_table$industry_Value, by=list(industry_name=industry_table$industry_name), FUN=min)
industry_table <- industry_table %>%  rename("industry_Value" = "x")

industry_table <- filter(industry_table, industry_Value > -440)
positive_industry <- industry_table %>% filter(industry_Value > 40)

positive_industry <- positive_industry[order(positive_industry$industry_Value),][1:5,]
positive_industry <- na.omit(positive_industry)

negative_industry <- industry_table %>% filter(industry_Value < 0) 
negative_industry <- negative_industry[order(negative_industry$industry_Value),][1:5,]
negative_industry <- na.omit(negative_industry)

```


Skill Migration

```{r}

skill_table <- subset(skill_migration, select = c(skill_group_name, net_per_10K_2017, net_per_10K_2018, net_per_10K_2019))
skill_table$skill_Value <- round((skill_table$net_per_10K_2017 + skill_table$net_per_10K_2018 + skill_table$net_per_10K_2019)/3, digits = 2)
skill_table <- subset(skill_table, select = c(skill_group_name, skill_Value))
skill_table <- skill_table %>%  filter(skill_Value > -400)
skill_table <- aggregate(skill_table$skill_Value, by=list(skill_name=skill_table$skill_group_name), FUN=min)
skill_table <- skill_table %>%  rename("skill_Value" = "x")

positive_skill <- skill_table %>% filter(skill_Value > 20) 
positive_skill <- positive_skill[order(positive_skill$skill_Value),][1:5,]
positive_skill <- na.omit(positive_skill)

negative_skill <- skill_table %>% filter(skill_Value < 0) 
negative_skill <- negative_skill[order(negative_skill$skill_Value),][1:5,]
negative_skill <- na.omit(negative_skill)

```


```{r}

# Countries Gaining From
Country_positive

# Countries Losing To
Country_negative

# Industries Gaining 
positive_industry

# Industries Losing
negative_industry

# Skills being gained
positive_skill

# Skills being lost
negative_skill

```

